export const emojiMapping = [
  '🦉',
  '🦒',
  '🐬',
  '🦜',
  '🐙',
  '🐐',
]

export const FEEDBACK_TYPE = {
  NONE: 'none',
  CORRECT: 'correct',
  INCORRECT: 'incorrect',
};

export const MODES = {
  NORMAL: 'normal',
  HARD: 'hard',
  DIABOLICAL: 'diabolical',
};

export const SOLUTIONS = `SITE TIES TIERS RITES TIRES TRIES SISTER RESIST RELISTS SLITHERS SHIRTLESS
SING SIGN GINS PINGS SPYING SPRINGY SPRAYING SPARINGLY
READ DEAR DARE AIRED RAIDER MARRIED ADMIRER DREAMIER REMAINDER
SUED USED DUES DUNES NUDES UNDIES INSURED SUNDRIES SIDEBURNS BURNSIDES
GETS GEST GENTS INGEST SIGNET TINGES SEATING TEASING SEDATING STEADING DESIGNATE
RECS CREST CORSET ESCORT SECTOR SCOOTER OUTSCORE COURTEOUS OUTSOURCE
TORE ROTE RETRO PORTER REPORT PRORATE PRAETOR OPERATOR CORPORATE
SEED DEES SPEED DEEPS ESPIED PRESIDE PERISHED WHISPERED
NORI IRON NOIR INTRO NITRO RATION ORATING RIGATONI MIGRATION
REPS SPREE PEERS PESTER PRESET PETERS STEEPER PRETEENS PRETENSE REPRESENT PRESENTER REPENTERS
PICS CLIPS SPLICE PICKLES PRICKLES CLERKSHIP
IONS COINS ICONS SCION SONIC COUSIN SUCTION MISCOUNT COSTUMING
ODDS DOSED DODGES GODDESS GODSENDS DODGINESS
DIVE VIED IVIED DIVIDE DIVINED DIVIDEND UNDIVIDED
GRIN RING GRAIN MARGIN ARMING ROAMING ORGANISM IGNORAMUS
TRUE TUNER NATURE CENTAUR UNCRATE UNTRACED UNDERACT UNCRATED UNCHARTED
GNAT TANG GRANT GRATIN RATING TARING RATTING RATTLING PRATTLING
REIN INERT INTER ORIENT PROTEIN POINTER ERUPTION IMPORTUNE
RARE REAR RACER CAREER TERRACE CATERER RETRACE RECREATE RACKETEER
SANE SEDAN DEANS ASCEND DANCES CANDIES DISTANCE SYNDICATE
LINE LIEN ALIEN FINALE INFLATE FILAMENT MINTLEAF FULMINATE
CART ACTOR CAPTOR CARTOP APRICOT TROPICAL PICTORIAL
BRAS BARS BRATS BAREST BASTER BREAST BARTERS ARBITERS BARRISTER
SITS STIRS STAIRS SITARS STRAINS ARSONIST ASSERTION SENORITAS
REIN REIGN RINGED DINGER GRINNED RENDING ENDURING UNDERSIGN SUNDERING
CASE ACES SCALE LACES CASTLE CLEATS ELASTIC LACIEST CASTILE CITADELS DIALECTS DISLOCATE
SERF REFS REEFS FREES REFERS FERRETS REFOREST FORESTER DEFROSTER
THIN HINT NIGHT THING HATING HALTING LATHING LATCHING HATCHLING
TORE ROTE ORATE OATER ORNATE ATONER SENATOR TREASON ATONERS RESONATE STONEWARE
DATE ACTED CADET CARTED CRATED REDACT TRACED REDCOAT CORDATE DEMOCRAT MOTORCADE
SEXT TEXTS SEXTET EXTENTS EXISTENT SIXTEENTH
STIR TRIOS RIOTS TORSI ROTIS SUITOR TOURIST OUTSTRIP PRINTOUTS OUTSPRINT
SEED DEES EASED SEATED TEASED SEDATE IDEATES DEVIATES SEDATIVE ADVERTISE
CURS CRUS CURDS CRUDS CURSED RECUSED REDUCES RESCUED SECURED SEDUCER CENSURED UNSECURED UNRESCUED
REVS VEERS VERSE SEVER SERVE SERVER REVERS REVERTS TRAVERSE HARVESTER
RIPS CRISP SCRIP CAPRIS SPACIER REPLICAS SPIRACLE CALIPERS PARTICLES
BEST BETS BENTS ABSENT BANTERS BARONETS ABSORBENT
DRIP PRIDE PRIED PRICED PIERCED PEDICURE PREJUDICE
TOES PESTO POETS ESTOP PRESTO POSTER TROPES REPOTS REPOST RESPOT REPORTS PRESORT PORTERS TROUPERS SUPPORTER
CRAG CARGO GARCON ORGANIC CAROMING ROMANCING
EARS SEAR ERAS SERA RAVES AVERS SAVER AVERTS STARVE VASTER BRAVEST VIBRATES VERBALIST
NARC CAIRN CRANIA ARNICA CARINA OCARINA RAINCOAT CARNATION
EVES VEES SIEVE REVISE GRIEVES DIVERGES DESERVING
TIRE RITE TIER RIVET INVERT VINTNER REINVENT INTERVENE
SETS SECTS CRESTS ACTRESS RECASTS CASTERS SCARCEST SCRATCHES
HITS THIS HEIST THEIRS HASTIER HARDIEST DISHWATER
VEAL VALE LAVE LEAVE REVEAL RAVELED SLAVERED ADVERSELY
TREE ENTER TREEN RELENT LECTERN ELECTRON TOLERANCE COETERNAL
DEAN ANTED ATTEND TAINTED ATTAINED ANTITRADE ATTAINDER
CART ACTOR RECOAT COATER EROTICA CREATION REACTION FORNICATE
ACES CASE LACES SCALE CAMELS MESCAL CALMEST CLIMATES METALLICS
ICON COIN TONIC NOTICE CONCEIT CONCERTI NECROTIC ACCRETION
DONE NODE ENDOW OWNED WOODEN SWOONED HOEDOWNS WOODHENS SNOWSHOED
SINS SNITS STEINS INSETS SNIDEST DISSENT TIDINESS INSISTED DISSIDENT
MEAN MANE AMEN NAME MEANT INMATE MINARET RAIMENT EMIGRANT MARKETING
SINE ANISE ARISEN RAVINES INVADERS VARNISHED
LACE CLEAR CARTEL CLARET RECTAL TREACLE RELOCATE CORRELATE
SEAR EARS ERAS SERA REARS RARES ERASER SEARER SERRATE RERATES REARREST ARRESTER TREASURER
DINE DEIGN DINGE TINGED DIETING EDITING IGNITED DINGIEST DIGESTION
HOGS GOSH GHOST GOTHS THONGS SHOTGUN GUNSHOT HANGOUTS SHOGUNATE
APED ADEPT TAPED DEPART PARTED PRATED PETARD TAPERED RETAPED PREDATE REPEATED DEPARTEE PREHEATED
SEAS CASES SCALES CLASHES SHACKLES SHELLACKS
MESS MESAS SEAMS MASSE SESAME MEASLES NAMELESS MALENESS LAMENESS SALESMEN MANELESS MEALINESS
MUTE UNMET MINUTE MINUET RUNTIME RUDIMENT IMPRUDENT
REIN INTER INERT TRINE UNITER TRIUNE NUTTIER UTTERING MUTTERING
SEND DENS NERDS RENDS DRONES SNORED ENDORSE CENSORED ENCODERS CRESCENDO
ACED DACE CASED CADETS REDACTS DETRACTS SCATTERED
PITA PAINT INAPT PLIANT PLAINT IMPLANT PLATINUM PENULTIMA
IONS SCION ICONS COINS SONIC COUSIN SUCTION MISCOUNT COLUMNIST
DIPS DRIPS SPIDER PRIDES PRISED SPIRED DIAPERS PRAISED ASPIRED DESPAIR PARADISE DISPARATE ASPIRATED
RIDS RIDES SIRED DRIES CIDERS DICERS SCRIED SIDECAR ASCRIBED BIRDCAGES
LASS SAILS AISLES ABSEILS BASSLINE LESBIANS BRAINLESS
SUPS PUSS SPURS PURSES SUPERS PERUSES PURENESS UNPRESSED SPEEDRUNS SUSPENDER
IONS IRONS NOIRS ROSIN GROINS SIGNOR SNORING MORNINGS MONSIGNOR
REAL EARL LEARN RENAL LINEAR NAILER RETINAL LATRINE RELIANT RELATION ORIENTAL RATIONALE
SITS SLITS SILTS LISTS ISLETS SLIEST STILES LISTENS ENLISTS SILENTS SALTINES SALIENTS STAINLESS SALTINESS
SIRE RISE RAISE ARISE PRAISE ASPIRE REPAIRS RASPIER RAPIERS PARRIES PRAIRIES DISREPAIR
RARE REAR RACER CARER CAREER CATERER TERRACE RECRATE RETRACE RECREANT CARPENTER
CASH CHAOS NACHOS ANCHORS RANCHOS MONARCHS HARMONICS
TEND DENT NOTED TONED DOCENT NOTICED DOCTRINE DIRECTION
SITE TIES HEIST TITHES THEIST ATHEIST HESITATE AESTHETIC
CUES CLUES ULCERS RECLUSE LECTURES CRUELEST CLUSTERED
ROOT TORO ROTOR TORPOR TROOPER OPERATOR TEARPROOF
DISS SIDES ISSUED DISUSE SUDSIER DESIROUS DISCOURSE
SEAS SEARS SNARES REASONS SENORAS PERSONAS TRANSPOSE PATRONESS
LENS LINES LIENS TINSEL LISTEN SILENT ENLIST INLETS SALIENT ENTAILS SALTINE LITANIES ALIENIST INELASTIC
TEEN EATEN NEATER ENTREAT RATTEEN TERNATE ANTEATER ALTERNATE
NICE CINE NIECE ENTICE GENETIC ERECTING GENTRICE CENTERING
TINT TAINT TITAN INTACT TITANIC CITATION DICTATION
SETS NESTS STEINS INSETS DISSENT SNIDEST DENTISTS DOTTINESS
GIST GITS STING TINGS GLINTS LISTING TILINGS SILTING STILTING SLITTING SPLITTING
ACES CASE SCALE LACES CLEATS CASTLE ELASTIC LACIEST LATTICES ATHLETICS
LACE CLEAR CARTEL CLARET RECTAL TREACLE RELOCATE PERCOLATE
NINE INNER DINNER GRINNED RENDING ENDURING UNRINGED UNDERLING
DENT TEND ANTED DETAIN FAINTED DEFIANT INFLATED DEFIANTLY
HALT LATH LATHE CHALET RELATCH LATCHER TRACHEAL CATHEDRAL
SNAG SANG NAGS ANGST GNATS TANGS AGENTS MAGNETS GARMENTS STREAMING MASTERING EMIGRANTS
HERD HEARD HARED ADHERE HEADER HEARTED EARTHED WREATHED WEATHERED
BELL LABEL BALLER BRAILLE LIBERAL RELIABLY BLEARILY LIBERALLY
EARS ERAS SEAR SERA ARSE DARES DEARS READS RAISED RESAID SHADIER AIRSHED RADISHES AIRSHEDS HARDINESS
ERRS RISER ROSIER SORRIER ORRERIES RESERVOIR
RIGS GRINS RINGS SIRING RISING VIRGINS REVISING SHIVERING
AIDS DAIS SAID STAID TRIADS TIRADES TARDIES ASTRIDE HARDIEST HEADFIRST
SODA ADOS ROADS DORSA ADORNS RANDOS ONWARDS SANDWORM MARKDOWNS
EATS EAST SATE TEAS SEAT TASE SAUTE SALUTE AMULETS MULETAS SIMULATE MUTILATES ULTIMATES STIMULATE
DUNE NUDE UNDER ENDURE ENURED TENURED DENTURE RETUNED DENATURE UNDERATE UNDEREAT UNEARTHED
SETS RESTS TRESS SISTER RESIST INSERTS SINTERS SINISTER DIRTINESS DISINTERS
REPS PRESS SPORES POSERS PROSES OPPRESS PROPOSES PORPOISES
INNS NINES TENNIS INTENSE TENNIES SENTIENT INTESTINE
STUD DUST DUETS DUTIES SUITED OUTSIDE TEDIOUS SOLITUDE CLOUDIEST
GUNS GNUS SUNG SNUG RUNGS GRUNTS STRUNG RUSTING TRUSTING THRUSTING
SIRS SRIS RISES SIRES SERIES REISSUE SEIZURES SUPERSIZE
SEAS OASES SEASON REASONS SENORAS BARONESS BROADNESS
ROWS SWORN WORSEN OWNERS RESOWN ROWENS SNOWIER BROWNIES WRISTBONE
EARN NEAR CRANE NECTAR TRANCE RECANT CANTER CENTRAL CLARINET INTERLACE
DELI LIED IDLE RILED SLIDER BRIDLES DRIBBLES SCRIBBLED
SOME POEMS MOPES POMES IMPOSE PROMISE SEMIPRO IMPOSTER MISREPORT IMPORTERS
HARE HEAR RHEA REACH ACHIER CHIMERA CHAIRMEN MACHINERY
TREE ENTER TERNE RELENT ETERNAL ENTERAL ANTLERED UNRELATED UNALTERED
RANT TARN TRAIN RATION ORATION TANDOORI ADORATION
NARC CRANE CANER NACRE CAREEN RECANE REENACT CRENATE CABERNET CELEBRANT
NOUN UNWON UNWORN UNSWORN RUNDOWNS SUNDOWNER UNDERSOWN
EONS ONES NOSE SONE OVENS VENOUS NERVOUS RAVENOUS SUPERNOVA
LONG LINGO LOGIN DOLING FOLDING FONDLING FOUNDLING UNFOLDING
EARS ERAS SEAR SERA ARSE REARS RARES RACERS CARERS ARCHERS CRASHER CHARTERS RECHARTS SCRATCHER
FEUD UNFED FONDUE FOUNDER FLOUNDER WONDERFUL UNDERFLOW
EASE ERASE HEARSE REHEARS SHEARER RESHARE REPHRASE SHARPENER
DEER REED CREED RECEDE DECREE ERECTED CENTERED PRECEDENT
TREE RETIE RETIRE RIVETER OVERTIRE OVERWRITE
SNAG NAGS SANG GAINS ASSIGN SIGNALS SAPLINGS SPANGLISH SPLASHING
SASH ASHES SHARES RASHES SHEARS HARNESS RASHNESS HARSHNESS
GAIN ACING CAKING LACKING CACKLING CLACKING CRACKLING
PORE ROPE REPO PRONE PERSON REOPENS OPENERS RESPONSE PRESEASON
TRUE UTTER TURTLE UTTERLY FLUTTERY BUTTERFLY
SETS NESTS STONES STENOS ONSETS NOSIEST SECTIONS CESSATION CANOEISTS SONICATES
DINE DEIGN DINGE ENDING GINNED DENTING TENDING UNTINGED INDULGENT
ALTO BLOAT OBLATE NOTABLE BALCONET COUNTABLE
SEED DEES REEDS SEDER DESERT DETERS RESTED TENDERS NERDIEST RESIDENT INSERTED SINTERED DISSENTER RESIDENTS TIREDNESS
ISLE LEIS LIES RILES SLIER REOILS OILERS ORIELS SPOILER PERILOUS REPULSION
SEAL SALE ALES LEAS LASE LASER EARLS RALES SERAL PEARLS EARLAPS PARABLES SPARABLE SEPARABLE
RIGS GRINS RINGS GRAINS SNARING GRANNIES EARNINGS ENGRAINS RANGINESS ANGRINESS
GERM GRIME GAMIER MIRAGE IMAGER RAGTIME MIGRATE EMIGRATE HERMITAGE
SIRS SRIS RISES SIRES RINSES SIRENS RESINS SERINS SNIPERS RESPINS RIPENESS PERKINESS
RICH CHIRP CIPHER CHIPPER CHOPPIER PROPHETIC
FRET AFTER RAFTED DAFTER FARTED DRAFTEE FEDERATE FEATHERED
ARMS RAMS MARS SMEAR MARES REAMS MASER REALMS REALISM MAILERS MEASLIER MISERABLE
TRUE ROUTE OUTRE OUTER DETOUR TOURED ROUTED REDOUT READOUT EDUCATOR OUTRACED UNDERCOAT
RANG GRAN GNAR GRAIN GAINER REGAIN NAGGIER GEARING ENRAGING ANGERING GARDENING GANDERING DERANGING
SEAS SEARS ARSES SWEARS ANSWERS RAWNESS WARINESS WEARINESS
ODOR DOOR ROOD RODEO MOORED ROOMED DOOMER MOTORED ODOMETER METEOROID
SURE RUES RUSE USER SUER ROUSE EUROS ROUES COURSE SOURCE CEROUS CROUSE CLOSURE COLURES ULCEROUS URCEOLUS CREDULOUS
SECT TECS CEST CHEST STECH TECHS STENCH CHASTEN SNATCHED STANCHED UNSCATHED STAUNCHED
DONE NODE CONED CODEN COINED CODEIN CONFIDE CONFINED CONFIDENT
RITE TIER TIRE REIT ITER IRATE ARITE TERAI TARIE RETIA RETINA RETAIN RATINE TANIER NATTIER NITRATE INTREAT ITERANT TERTIAN MARTINET TETRAMIN INTERMAT TERMINATE
CUES ECUS CURSE CURES SUCRE ECRUS CRUSE ULCERS CRUELS LUCRES LURCHES SLOUCHER LECHEROUS
NERD REND DERN DINER RIDEN RUINED INURED DIURNE UNRIDE INURNED UNFRIEND UNREFINED
EGOS GOES SEGO OGRES GORES SOGER GORSE GOERS GROUSE ROUGES ROGUES ERUGOS RUGOSE BROGUES BURGEONS SUBREGION
LAIN NAIL LINA ANIL ALIN ALIGN LIANG LANGI LINGA LIGAN ALGIN LAYING GAINLY ANGRILY RALLYING GLARINGLY
TERN RENT INERT INTER RETIN NITRE TRINE NITER ENTIRE TRIENE RETINE NEITHER THEREIN ENHERIT ETHERIN THEREMIN INTERMESH THEREMINS
IONS SION ICONS SCION COINS SONIC OSCIN CIONS COUSIN SUCTION UNSTOIC DISCOUNT CONDUITS NOCTUIDS CUSTODIAN
STIR RIST RITES TIERS TIRES TRIES RESIT STERI TRIBES BITERS BESTIR BISTER BISTRE BITTERS TRIBUTES BUTTERIS SUBMITTER
TOES PESTO POETS STOEP TOPES STOPE ESTOP PRESTO POSTER TROPES REPOTS REPOST RESPOT STOPER TOPERS SPORTED DEPORTS REDTOPS DOORSTEP TORPEDOS DROOPIEST DEPOSITOR
PODS UPDOS SOUPED PSEUDO SPOUTED OUTSPED OUTSPEND UNPOSTED UNSPOTTED
HEAR HARE RHEA EARTH HEART HATER RATHE REHEAT HEATER HEREAT AETHER WEATHER WHEREAT WREATHE WREATHED HEADWATER WATERHEAD
ROAN ORNA APRON PATRON TARPON PARTON OPERANT PRONATE PROTEAN COPARENT PORTANCE PROCREANT COPARTNER
RUNE RUEN TUNER ENRUT URENT NATURE OUTEARN OUTRANGE ENTOURAGE
ROAD ORAD ADORE OARED OREAD ORDEAL RELOAD LOADER LEOTARD DELATOR TAILORED IDOLATER EDITORIAL
REAR RARE RACER CARER CRARE CAREER CREAMER AMERCER CREAMERY MERCENARY
TORN TRON NITRO INTRO RATION AROINT RAINOUT CURATION NOCTURIA INCUBATOR
GNAT TANG GANT GIANT TIANG TANGI HATING ATHING ANIGHT HALTING LATHING THINGAL FANLIGHT NIGHTFALL
SUED USED DUES DUETS STUDE RUSTED RUDEST DUSTER DERUST DUSTIER STUDIER STUPIDER DISPUTER DISREPUTE REDISPUTE
SPIT PITS TIPS PIST PITAS TAPIS SPAIT PAINTS PATINS PINTAS PTISAN PANTIES SAPIENT SPINATE PATINES THESPIAN PANTHEIST
ISLE LEIS SILE LIES RILES SLIER RIELS LIERS PLIERS PERILS LISPER SIRPLE SPILER TRIPLES RESPLIT PRIESTLY SPLINTERY
TEES STEEL SLEET TEELS STELE SLETE TELES LEETS NESTLE RELENTS NESTLER LISTENER RELISTEN SILENTER REENLIST RESILIENT
TREE REET TEER RETE ENTER RENET TREEN TERNE NETER RENTE ENTREE TEENER RETENE ETERNE RENTEE PRETEEN TERPENE REPENTED REPETEND PRETENDER
DUNE NUDE UNDE UNDER UNRED RUNED NUDER ENDURE ENURED DURENE TENURED DENTURE RETUNED UNTREED UNDEREAT UNDERATE DENATURE UNTREATED
SNAG SANG NAGS GAINS ASSIGN CASINGS CAGINESS CARESSING
RING GRIN GIRN GRAIN GARNI AGRIN RATING GRATIN TARING ORATING RIGATONI RIGATION TAILORING LARGITION GRATIOLIN
SONS NOSES SONES SENSO LESSON LIONESS INSOLES LESIONS EPSILONS POINTLESS
SINS SINES NISSE SINEWS WINLESS SWINDLES WILDNESS WINDLESS SNOWSLIDE
ERRS REARS RARES SERRA ERASER REAPERS SPEARER REPHRASE PRESHARE SHARPENER RESHARPEN
REAR RARE RACER CARER CRARE CRATER TRACER ARRECT RECART CARTER ERRATIC CIRRATE CRITERIA GERIATRIC
TEES THESE SHEET THREES ETHERS SHELTER HOSTELER HOLSTERED
RAID ARID AIRED AIDER REDIA IRADE TIRADE TRIAGED GRADIENT TREADING REDATING DERATING DENIGRATE ARGENTIDE GRATINEED DINERGATE
TREE RETE EATER ARETE CREATE CERATE ECARTE TREACLE BRACELET TRACEABLE
RITE TIER TIRE ITER IRATE TERAI RETIA SATIRE STRIAE TERAIS REALIST SALTIER RETAILS SALTIRE SLATIER LATRINES ENTRAILS RETINALS RATLINES TRENAILS REINSTALL INSTALLER
LAGS GALS SLAG SLANG GLANS ALIGNS SIGNAL LIANGS ALGINS LASING LINGAS SCALING LACINGS CASTLING CATLINGS NOSTALGIC
SEAS ASSE SEARS ARSES RASSE SNARES SARSEN REASONS SENORAS PERSONAS RESPONSA ASPERSION
ACNE CANE ENACT NECTAR TRANCE RECANT CANTER CENTRA CARNET CERTAIN CITREAN NACRITE CREATION REACTION ACTIONER CERATION ANEROTIC MANTICORE CREMATION
SHIN SINH CHINS CHAINS CASHING CHASING SCATHING SNATCHING STANCHING
ACES CASE SCALE LACES ALECS CASTLE CLEATS ECLATS CALMEST CAMLETS CLIMATES CLEMATIS METICALS ALCHEMIST
CLAN CLANG GLANCE CANGLE ANGELIC GALENIC ANGLICE CLEANING ENLACING CONGENIAL
AIRS SARI RAIS RIAS RAISE ARISE SERAI ARMIES RAMIES MAESTRI IMARETS MISRATE STEAMIER EMIRATES TIMESAVER
ROSE ORES ROES SORE SNORE SENOR NOSER SERON GONERS GENROS IGNORES REGIONS SIGNORE RESOLING SOLDERING
MESS SEAMS MESAS MASSE SHAMES MASHES MESSIAH MASHIES EMPHASIS MISSHAPE MISSHAPEN
RILE LIRE LIER RIEL LITER LITRE RELIT TILER RETAIL ATELIER TIRALEE LITERATE LATERITE RETALIATE ALITERATE
LINT GLINT TILING LIFTING FLITING FLITTING FITTINGLY
SETS NESTS STONES STENOS ONSETS SETONS NOSIEST TENSIONS SENSATION
SINE SINGE SENGI RESIGN REIGNS SINGER SIGNER RESING LINGERS SLINGER RIESLING RESILING RELIGIONS
RAIN RANI CAIRN CRAIN ARNICA CRANIA ACINAR NARICA CARINA OCARINA MACARONI MAROCAIN ARMONICA PANORAMIC
SAND ANDS HANDS DANISH SANDHI SHADING DASHING HEADINGS DEASHING SHEADING ANGUISHED
IONS NOISE EOSIN SENIOR NOSIER IRONES VERSION REVISION INVERSION
TEES STEED DEETS SEDATE TEASED SEATED STEAMED MEDIATES DEFEATISM
DONE NODE NOTED TONED TENDON INTONED ANOINTED ANTINODE NOMINATED DENTINOMA
FEND FIEND FINED DEFINE INFEED FEINTED INFECTED DEFICIENT
SUES USES USERS RUSES SUERS SURES NURSES UNDRESS SUNDERS RESOUNDS SOUNDERS DOURNESS ROUNDNESS
SETS RESTS TRESS STRESS ASSERTS TRASSES TRESPASS SPARSEST STRAPLESS PSALTRESS
RENT TERN TREND TENDER RENTED DENTER TENURED DENTURE UNTREED RETUNED RETURNED UNDERRATE RENATURED
BIAS BASIL BAILS BIALYS SYLLABI SIBYLLA SYLLABIC BASICALLY
TILE LITE TELI TEIL LEGIT GIMLET MELTING LIGAMENT ALIGNMENT LAMENTING
APED ADEPT TAPED DEPART PARTED PRATED PETARD PREDATE TAPERED RETAPED REPEATED DEPARTEE DEEPWATER
VIES VISE VEINS VINES SNIVEL LIVENS UNVEILS EVULSION ENVIOUSLY
TREE RETE ENTER TREEN TERNE RENTE RELENT ETERNAL TELERAN TENERAL ALTERNE ENTERAL ANTLERED UNRELATED UNALTERED
SIGN SING GINS DINGS SIDING SHINDIG DISHING DINGHIES SHIELDING
LEND LADEN ELAND NALED LEADEN LEANED ENABLED DENIABLE BREADLINE
SIRS SRIS SIRES RISES SERIFS FISSURE FUSSIER SURFEITS SURFIEST FRUITLESS RESISTFUL
DIRT TIRED TRIED TIERED REEDIT DIETER RETIED DEMERIT MERITED RETIMED MITERED DIMETER REMITTED DETRIMENT
EARS ERAS SEAR SERA ARSE NEARS EARNS SNARE SANER ARISEN ARSINE ARSENIC ARCSINE CARNIES CANISTER SCANTIER CISTERNA RECASTING
SOOT BOOST BOOTS OBOIST BONITOS OBTUSION OBTRUSION
RIDS DRIES RIDES SIRED RESID SLIDER SIDLER IDLERS BRIDLES BRISTLED DRIBLETS BLISTERED
ICES SINCE CINES COSINE OSCINE CONIES CRONIES RECOINS COINERS CORNIEST CORTISONE
DISS SIDES ISSUED DISUSE GUSSIED DINGUSES GAUDINESS
PACT PATCH HAPTIC PHATIC HEPATIC APHETIC PASTICHE SCAPHITE PISTACHE WHITECAPS
ONCE CONE COVEN NOVICE INVOICE EVICTION COGNITIVE
EARN NEAR CRANE CANER NACRE CRENA NECTAR TRANCE RECANT CANTER CENTRA CARNET CENTAUR UNCRATE UNTRACE TRUNCATE UTTERANCE
RIDS DRIPS PRIDES SPIDER SPIRED DESPAIR DIAPERS ASPIRED PRAISED PARADISE DISAPPEAR APPRAISED
DICE ICED CEDI CITED EDICT DECEIT ENTICED INCEPTED CENTIPEDE
ICES SINCE CINES NIECES SINCERE SERECIN GENERICS SCREENING SECERNING
PEER CREEP CREPE PIERCE RECIPE PIECER RECEIPT DECREPIT PREDICATE
ROTE TORE RETRO RETORE ERECTOR RECEPTOR PROCREATE
NICE CINE MINCE INCOME GENOMIC COMINGLE WELCOMING
CHAI CHIA CHAIN CHINA ACHING CASHING CHASING SCATHING NIGHTCAPS
NUTS TUNS STUN STUNT TAUNTS MUTANTS TANTRUMS TRUSTMAN TRANSMUTE
GIST GITS STING TINGS INGEST TINGES STINGE SIGNET IGNITES NIGHTIES THINGIES HEISTING HYGIENIST
SUES USES RUSES USERS SUERS DURESS SUDSER UNDRESS SUNDERS SOUNDERS RESOUNDS DOURNESS UNCROSSED
OILS SOIL SILO SOLI LOINS LIONS NOILS TONSIL LOTIONS SOLITON LOONIEST OILSTONE NEOLOGIST ENOLOGIST
DRUG URGED ARGUED GUARDED UNGRADED UNDERGRAD UNDERDRAG
VANE NAVE VENA RAVEN TAVERN VETERAN RELEVANT LEVANTER PREVALENT
SEAS ASSE SEARS ARSES RASSE ERASES TEASERS RESEATS TESSERA SEATERS TEARLESS RESLATES STEALERS TESSELAR TASSELER ALERTNESS
GENE GENRE GREEN REGENT GERENT INTEGER TREEING REGIMENT METERING GERMINATE GERMANITE RETEAMING
DATE CADET ACTED ECTAD REDACT TRACED CRATED CARTED CEDRAT REACTED CATERED CREATED CERATED CEDRATE TERRACED CRATERED RETRACED REFRACTED
RANG GRAN GNAR GRAIN AGRIN RARING ROARING RAZORING ORGANIZER
GALE ANGEL ANGLE GLEAN GENAL GLANCE CONGEAL COLLAGEN COLLEGIAN ALLOGENIC
ICES SPICE EPICS PIECES SPECIE SPECIES ECLIPSES PRICELESS PRESLICES
NERD REND TREND TINDER INTRUDE UNTIRED UNTRIED REUNITED INDENTURE
ORCS ROCS SCOUR COURSE SOURCE CEROUS CLOSURE COLURES COUPLERS SUPERCOOL
STIR TIERS RITES TIRES TRIES SATIRE STRIAE TERAIS ARTSIER TARRIES TARSIER ARTERIES CAREERIST TRACERIES
NEAT ANTE ETNA MEANT AMENT STAMEN AMENTS MEANEST MATINEES ETAMINES SEMINATE MEATINESS AMNESTIES
PIES PISE SIPE POISE PONIES OPINES ESPINO PEONIES PIONEERS ISOPRENE PENSIONER
SALT SLAT ALTS LATS LAST TALKS STALK LATKES LASKET TACKLES PLACKETS SKEPTICAL
SEED DEES SEDER REEDS SCREED CREEDS CEDERS RECEDES DECREES SECEDER DECREASE DESECRATE DECASTERE
SNIT TINS NITS MINTS MANTIS MATINS TSUNAMI NATURISM RUMINATES
REAL EARL RALE LATER ALTER ALERT ARTEL RATEL RETAIL TAILER REALITY TEARILY IRATELY INTERLAY INTERPLAY PAINTERLY
GONG GOING NOGGIN LONGING LOUNGING YOUNGLING
LICE CEIL RELIC RECOIL COILER CALORIE CARIOLE COALIER LORICAE COLINEAR ACROLEIN PORCELAIN
DEER REED CREED CERED CEDER RECODE PROCEED PRECODE RECOUPED PROCEDURE REPRODUCE
DICE ICED CEDI CHIDE INCHED CHINED NICHED CHAINED ECHIDNA HACIENDA ENCHILADA
AIRY RIYAL RACILY LYRICAL RACIALLY CAPILLARY
DATE DEALT DELTA DENTAL SLANTED DENTALS WETLANDS WASTELAND
REAL EARL RALE LEARN RENAL LINEAR LARINE NAILER RENAIL INHALER HERNIAL HARDLINE HEADLINER
SIGN SING GINS GAINS ASKING KIANGS GASKIN SNAKING SHANKING UNSHAKING
CATS SCAT ACTS CAST SCANT CANTS ANTICS NASTIC INCANTS STANNIC SANCTION CONTAINS CANONIST ACTINONS STANCHION
TOES PESTO POETS STOPE ESTOP TOPES PRESTO POSTER TROPES REPOTS REPOST RESPOT STOPER TOPERS RIPOSTE ROPIEST REPOSIT SPORTIER PORTSIDER POSTRIDER
TORN INTRO NITRO ORIENT TONIER NORITE ROUTINE NEUROTIC UNEROTIC INTRODUCE REDUCTION
ROBS ORBS BROS SORB SOBER BORES ROBES STROBE SORBET BOATERS SORBATE BORATES REBATOS BOASTER BARONETS OBSERVANT
RIND DRAIN DINAR NADIR RANID RAINED HANDIER ADHERING HEADRING GARNISHED
TREE RETE ERECT RECITE CERITE TIERCE COTERIE METEORIC GEOMETRIC
SILK ILKS SLINK LINKS KILNS LIKENS INKLES SILKEN INKLESS KINLESS SEALSKIN LANKINESS
TENS NETS SENT NEST VENTS INVEST INVITES VINIEST VEINIEST INVITEES INTENSIVE
TOES STOKE TOKES SOCKET POCKETS LOCKSTEP STOCKPILE
RIGS RINGS GRINS RESIGN REIGNS SINGER SIGNER RESING CRINGES SCRINGE GRINCHES SEARCHING
RUDE RUED DRUPE PRUDE DUPER PURRED PROUDER PROTRUDE CORRUPTED
LOSE SLOE SOLE OLES SOLVE LOVES VOLES OLIVES VOILES VIOLETS NOVELIST INSOLVENT
LENS LINES LIENS LENIS TINSEL LISTEN SILENT ENLIST INLETS TINGLES GLISTEN SINGLET NESTLING SINGLETON
TREE RETE THREE THERE ETHER HEATER REHEAT AETHER HEREAT HECTARE TEACHER CHEATER RETEACH RECHEAT CATHETER CHARETTE CHATTERER
SINE FINES FEIGNS FRINGES FINGERS REFUSING SUFFERING
REPS PRESS SPIRES PISSER SPIERS SNIPERS PRINCESS CRISPENS CRISPNESS
REEL LEER ELDER DEALER LEADER LEARNED LAVENDER UNRAVELED
EASE ERASE TEASER RESEAT EATERS ARETES SEATER SAETER REPEATS REPASTE RETAPES PREHEATS THERAPIES
TOSS SOTS COSTS SCOUTS CUSTOS LOCUSTS CONSULTS COUNTLESS
TEED DEET DETER TREED TEARED REDATE DERATE CREATED CATERED REACTED CEDRATE CERATED REDACTED DECORATED
MESS STEMS SMITES TMESIS MISSET MISSTEP PASTIMES IMPASTES SHIPMATES STEAMSHIP
NOSH HONS HORNS SHORN RHINOS NOURISH ROUNDISH SHROUDING
SINE LINES LIENS LENIS SINGLE LEGIONS LONGIES LINGOES SIDELONG GODLINESS
DEER REED ELDER LEERED REELED REVELED LEVERED REVEALED EVERGLADE LEVERAGED
ONCE CONE RECON CRONE CORNET TROUNCE RECOUNT COUNTER CORNUTE NOCTURNE ENCOUNTER
EARS ERAS SEAR SERA ARSE NEARS EARNS SNARE SANER ANGERS RANGES HANGERS REHANGS SHEARING HEARINGS HEARSING SHRINKAGE KASHERING
READ DARE DEAR DREAD DARED ADDER READD DEADER REDHEAD ADHERED THREADED DEHYDRATE
SEAS ASSE SEARS ARSES RASSE SNARES SARSEN SANDERS SARDINES ARIDNESS READINESS
SIGN SING GINS RINGS GRINS GRAINS MARGINS MIGRANTS SMARTING HAMSTRING
GAIN ALIGN ALGIN LAYING GAINLY ALLYING TALLYING HALTINGLY
REAL EARL RALE LATER ALTER ALERT ARTEL RATEL CARTEL CLARET RECTAL TREACLE RELOCATE LATECOMER
DUOS OUDS DOUSE SOUPED PSEUDO SPOUTED OUTSPED OUTSPEND UNPOSTED UNSTOPPED
GIST GITS STING TINGS GIANTS SATING SALTING SLATING LASTING STALING STARLING STARTLING RATTLINGS
USES SUES USERS RUSES SUERS SURES NURSES INSURES SUNRISE SUNRISES RUSTINESS
STIR SHIRT THIRST HITTERS TITHERS THEORIST THORITES WORTHIEST
ROTE TORE RETRO RETORE ERECTOR RECEPTOR PRECEPTOR
GERM GRIME MIRAGE GAMIER IMAGER MAIGRE GRIMACE CREAMING AMERCING EMBRACING CAMBERING
SLUR SURLY SURELY ELUSORY YOURSELF PROFUSELY
CRAP CARP PACER RECAP CAPER PREACH EPARCH CHEAPER PEACHIER PARCHEESI EPARCHIES`
